config/routes.rb
Rails.application.routes.draw do
  resources :structures
  resources :classifications
  resources :accessories
  resources :accessories_cars
  resources :brands
  resources :cars
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accessories_car.rb
class AccessoriesCar < ApplicationRecord
  belongs_to :car
  belongs_to :accessory
end

app/controllers/accessories_cars_controller.rb
class AccessoriesCarsController < ApplicationController
  before_action :set_accessories_car, only: [:show, :edit, :update, :destroy]

  # GET /accessories_cars
  # GET /accessories_cars.json
  def index
    @accessories_cars = AccessoriesCar.all
  end

  # GET /accessories_cars/1
  # GET /accessories_cars/1.json
  def show
  end

  # GET /accessories_cars/new
  def new
    @accessories_car = AccessoriesCar.new
  end

  # GET /accessories_cars/1/edit
  def edit
  end

  # POST /accessories_cars
  # POST /accessories_cars.json
  def create
    @accessories_car = AccessoriesCar.new(accessories_car_params)

    respond_to do |format|
      if @accessories_car.save
        format.html { redirect_to @accessories_car, notice: 'Accessories car was successfully created.' }
        format.json { render :show, status: :created, location: @accessories_car }
      else
        format.html { render :new }
        format.json { render json: @accessories_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories_cars/1
  # PATCH/PUT /accessories_cars/1.json
  def update
    respond_to do |format|
      if @accessories_car.update(accessories_car_params)
        format.html { redirect_to @accessories_car, notice: 'Accessories car was successfully updated.' }
        format.json { render :show, status: :ok, location: @accessories_car }
      else
        format.html { render :edit }
        format.json { render json: @accessories_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories_cars/1
  # DELETE /accessories_cars/1.json
  def destroy
    @accessories_car.destroy
    respond_to do |format|
      format.html { redirect_to accessories_cars_url, notice: 'Accessories car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessories_car
      @accessories_car = AccessoriesCar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accessories_car_params
      params.require(:accessories_car).permit(:name)
    end
end

app/helpers/accessories_cars_helper.rb
module AccessoriesCarsHelper
end

app/views/accessories_cars/_form.html.erb
<%= form_with(model: accessories_car, local: true) do |form| %>
  <% if accessories_car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accessories_car.errors.count, "error") %> prohibited this accessories_car from being saved:</h2>

      <ul>
        <% accessories_car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accessories_cars/edit.html.erb
<h1>Editing Accessories Car</h1>

<%= render 'form', accessories_car: @accessories_car %>

<%= link_to 'Show', @accessories_car %> |
<%= link_to 'Back', accessories_cars_path %>

app/views/accessories_cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accessories Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories_cars.each do |accessories_car| %>
      <tr>
        <td><%= accessories_car.name %></td>
        <td><%= link_to 'Show', accessories_car %></td>
        <td><%= link_to 'Edit', edit_accessories_car_path(accessories_car) %></td>
        <td><%= link_to 'Destroy', accessories_car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessories Car', new_accessories_car_path %>

app/views/accessories_cars/new.html.erb
<h1>New Accessories Car</h1>

<%= render 'form', accessories_car: @accessories_car %>

<%= link_to 'Back', accessories_cars_path %>

app/views/accessories_cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @accessories_car.name %>
</p>

<%= link_to 'Edit', edit_accessories_car_path(@accessories_car) %> |
<%= link_to 'Back', accessories_cars_path %>